# Generated by Django 4.1.1 on 2022-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='music_image/')),
                ('name', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='musics/')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3)),
                ('artist', models.CharField(max_length=50)),
            ],
        ),
    ]
